#!/bin/bash
astyle --style=linux --indent=force-tab=8 --max-code-length=80 --unpad-paren --pad-oper --pad-header --align-pointer=name "$@"
cat $* |sed -r 's,\t,.......|,g' |egrep --color -n -m11 ".{81}" -B1

