#!/bin/sh
#
# Copyright (c) Andrey Shvetsov, 2017
#

USAGE=""
if [ -z "$GUILT_VERSION" ]; then
    echo "Invoking `basename $0` directly is no longer supported." >&2
    exit 1
fi

_main() {
    if [ $# -gt 0 ]; then
        usage
    fi

    echo "$GUILT_DIR/$branch"
}
