#!/bin/sh
#
# Copyright (c) Andrey Shvetsov, 2017
#

usage() {
    echo "Usage: $0 patch" >&2
    exit 1
}

_main() {
    if [ $# -gt 1 ]; then
        usage
    fi

    local qpath="$(guilt path)"
    local N="${1:-$(guilt next)}"

    if [ ! -f "$qpath/$N" ]; then
        usage
    fi

    cat "$qpath/$N"
}

_main "$@"
