#!/bin/bash
APPNUM=$(guilt app |wc -l)
(
	echo; guilt unapplied |tac
	echo; git status -s -uno
	echo; git log --color -$APPNUM --oneline |tee /dev/null
	echo; git log --color -1 HEAD~$APPNUM --oneline --decorate |tee /dev/null
) |uniq |tail -n +2
