#!/bin/bash
set -o nounset
set -o errexit

# TOP=$(guilt top)
# [[ -z "$TOP" ]] && { echo "no patches applied, bye!"; exit; }
# echo "current patch is $TOP"

NEXT="$(guilt next)"
[[ -z "$NEXT" ]] && { echo "no next patch, bye!"; exit; }

NEXTv=$(echo "${NEXT}.v1" |sed -r "s,([.]v[0-9]+).v1$,\1,")
NEXTv=$(echo "$NEXTv" |sed -r "s,[0-9]+$,,")$((1 + $(echo "$NEXTv" |sed -r "s,.*v,,")))

IMPLANT=""
if [ "${1:-x}" = "-i" ]; then
  shift
  IMPLANT=y
fi

EXTRACT="xpl-${1:-$(date +%Y-%m-%d-%H%M%S)}"

LOG="$(guilt path)/.xplant.log"
date >>"$LOG"

echo "$ guilt new -f $EXTRACT" >>"$LOG"
guilt new -f "$EXTRACT" >>"$LOG"

echo "$ git diff ..HEAD~1 >$(guilt path)/revert_$EXTRACT" >>"$LOG"
git diff ..HEAD~1 >"$(guilt path)/revert_$EXTRACT"

echo "$ guilt new $NEXTv" >>"$LOG"
guilt new "$NEXTv" >>"$LOG"

echo "$ guilt fold revert_$EXTRACT" >>"$LOG"
guilt fold "revert_$EXTRACT" >>"$LOG"

echo "$ guilt fold $NEXT" >>"$LOG"
guilt fold "$NEXT" >>"$LOG"

echo "$ guilt pop" >>"$LOG"
guilt pop >>"$LOG"

if [ -n "${IMPLANT}" ]; then
  echo "$ guilt pop" >>"$LOG"
  guilt pop >>"$LOG"

  echo "$ guilt fold $(guilt next)" >>"$LOG"
  guilt fold $(guilt next) >>"$LOG"
fi

echo >>"$LOG"
echo "ok"
